# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "bash"

[plugins.fzf]
local = '~/.config/fzf'
use = ['fzf.bash']

[plugins.fzf-tab-completion]
github = 'lincheney/fzf-tab-completion'
use = ['fzf-bash-completion.sh']

[plugins.fzf-tab-completion-bind]
inline = 'bind -x "\"\t\": fzf_bash_completion"'

[plugins.bash-load]
local = '~/.config/bash/load'
use = ['*.sh']

[plugins.starship]
inline = 'eval "$(starship init bash)"'
